#!/bin/python3

def check(l,k):
    p=[0 for x in range(1000)]
    for i in l:
        p[i]=p[i]+1
    for i in l:
        p[i]-=1
        if p[k-i]>0:
            return True
        p[i]+=1
    return False
    
if __name__ == '__main__':
    l=list(map(int,input().split()))

    k=int(input())

    print(check(l,k))
